services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sd_svc_auth
      POSTGRES_USER: sd_svc_auth_user
      POSTGRES_PASSWORD: sd_svc_auth_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sd_svc_auth" ]
      interval: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  sd-svc-auth:
    # platform: linux/amd64
    image: shinoda4/sd-svc-auth:latest
    depends_on:
      - postgres
      - redis
    command: ["/scripts/wait-for-deps.sh"]

    environment:
      DATABASE_DSN: postgres://sd_svc_auth_user:sd_svc_auth_password@postgres:5432/sd_svc_auth?sslmode=disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: 
      SERVER_HOST: 0.0.0.0
      HTTP_PORT: 8080
      GRPC_PORT: 50051

      JWT_SECRET: replace_with_a_strong_secret
      JWT_EXPIRE_HOURS: 72

      EMAIL_ADDRESS: lindesong666@gmail.com
      EMAIL_PASSWORD: hdpxosifimlxvqzv

      RESET_PASSWORD_URL: http://localhost:8080/api/v1/reset-password

    ports:
      - "8081:8080"
      - "50051:50051"

volumes:
  pgdata:
  redisdata:
