apiVersion: v1

kind: ConfigMap
metadata:
  name: sd-svc-auth-configmap
data:
  POSTGRES_DB: sd_svc_auth
  POSTGRES_USER: sd_svc_auth_user
  DATABASE_DSN: postgres://sd_svc_auth_user:sd_svc_auth_password@postgres:5432/sd_svc_auth?sslmode=disable
  REDIS_ADDR: redis:6379
  SERVER_HOST: 0.0.0.0
  HTTP_PORT: "8080"
  GRPC_PORT: "50051"

  # JWT_SECRET: replace_with_a_strong_secret
  JWT_EXPIRE_HOURS: "72"

  # EMAIL_ADDRESS: lindesong666@gmail.com
  # EMAIL_PASSWORD: hdpxosifimlxvqzv

  RESET_PASSWORD_URL: http://localhost:8080/api/v1/reset-password
