apiVersion: v1

kind: Secret

metadata:
  name: sd-svc-auth-secret

stringData:
  EMAIL_ADDRESS: lindesong666@gmail.com
  EMAIL_PASSWORD: hdpxosifimlxvqzv
  JWT_SECRET: replace_with_a_strong_secret
  REDIS_PASSWORD: sd_svc_auth_password
  POSTGRES_PASSWORD: sd_svc_auth_password

type: Opaque
