apiVersion: v1
kind: Service

metadata:
  name: sd-svc-auth-service

spec:
  selector:
    app: sd-svc-auth
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc # ğŸ’¡ æ–°å¢ï¼šgRPC ç«¯å£å®šä¹‰
      port: 50051 # å¤–éƒ¨ Pod è®¿é—® sd-svc-auth-service:50051
      targetPort: 50051 # æ˜ å°„åˆ°å®¹å™¨å†…éƒ¨çš„ 50051 ç«¯å£
      protocol: TCP
